# Service definition file to connect pod to external world
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: 4000
     targetPort: 4000
     nodePort: 30001
  selector:
     app: myapp
  externalIPs:
    - IP
